run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - deadcode
    - varcheck
    - structcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: todo-api

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  sort-results: true